DROP TABLE IF EXISTS ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS (ID INT AUTO_INCREMENT PRIMARY KEY, MATRICULA INT NOT NULL, NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL);

INSERT INTO ODONTOLOGOS (MATRICULA, NOMBRE, APELLIDO) VALUES (11442545, 'Juan', 'Diaz');
INSERT INTO ODONTOLOGOS (MATRICULA, NOMBRE, APELLIDO) VALUES (11442558, 'Jorge', 'Corrales');
INSERT INTO ODONTOLOGOS (MATRICULA, NOMBRE, APELLIDO) VALUES (11154645, 'Kate', 'LLano');
INSERT INTO ODONTOLOGOS (MATRICULA, NOMBRE, APELLIDO) VALUES (11856223, 'Maria', 'Ruiz');

